# Generated by Django 2.2.9 on 2020-01-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noc', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=30)),
                ('notes', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.SmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.SmallIntegerField()),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('team', models.CharField(max_length=40)),
                ('games', models.CharField(max_length=40)),
                ('year', models.SmallIntegerField()),
                ('season', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('sport', models.CharField(max_length=40)),
                ('event', models.CharField(max_length=40)),
                ('medal', models.CharField(max_length=10)),
                ('noc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Noc')),
            ],
        ),
    ]
