# Generated by Django 2.2.9 on 2020-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='game',
        ),
        migrations.AddField(
            model_name='event',
            name='event',
            field=models.CharField(default=True, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='medal',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.CharField(default=True, max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.CharField(default=True, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.CharField(default=True, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(default=True, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='games',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
