# Generated by Django 2.2.9 on 2020-02-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='identification',
            field=models.IntegerField(),
        ),
    ]
