# Generated by Django 2.2.9 on 2020-01-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200131_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='games',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='medal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='season',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='sex',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='sport',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='team',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='noc',
            name='noc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='noc',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
