# Generated by Django 2.2.9 on 2020-02-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200201_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='age',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
