# Generated by Django 2.2.9 on 2020-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200201_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comitees',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
